### ISSUE TITLE
Presentations License

### ISSUE THREAD

**Issue by Hippyjake** [CochiseLinuxUsersGroup/Presentations#1]
What is your thought on Open Source Licenses for Presentations?
A good place to start is http://choosealicense.com/licenses/ They cover all the OSS Licenses.

Should we give members a choice of license to publish under, if we host it? A small list, of say 3 or 4 to choose from?

**I will state my thoughts after some debate** _I don't want to sway anyone_

@MajB @paulbe any thoughts?

**Comment by paulbe** [comment]
I like the idea of letting people choose their license.  I personally would
like to public domain any presentations I do.  I would try to get people to
use Apache, GPL, MIT, or Public Domain.  That will ultimately be their
choice.  Also some people may not even want their talk posted, we should
cater to whatever the presenter wants to do as to welcome any talks to the
group.

**Comment by MajB** [comment]
If they do not want the presentation published (OK - we won't publish).  If they don't care, then it is in our hands and I have no preference.  The stuff that we are doing probably has been gleaned from numerous sources.  If and when we get outsiders to come and present then we may have a different situation, but I really don't think it is going to matter one way or the other.

**Comment by MajB** [comment]
OBE
